### ISSUE TITLE
output debug symbols for STM8

### ISSUE THREAD

**Issue by mkSaBtsy** [github0null/eide#162]
I'm still struggeling with debugging a STM8S target. It seems to me that eide doesn't pass the proper arguments to sdcc for generating debug symbols. The STM8 debug plugin complains about DWARF error:

![grafik](https://user-images.githubusercontent.com/38809530/189499267-289393f0-0465-4e3d-854c-90058c197630.png)

If I compile the program manually by entering the commands into the terminal the debug plugin works like expected.

![grafik](https://user-images.githubusercontent.com/38809530/189499805-c739937d-61a4-492d-b965-de2719304a14.png)
![grafik](https://user-images.githubusercontent.com/38809530/189499898-f227da61-7f98-46c1-bf5d-b7495baa8637.png)

Unfortunately I sill haven't found out how to output the exact commands and arguments that are used when compiling.

**Comment by github0null** [comment]
Maybe you need apply `--debug` params to `Builder Options` -> `Global Options` -> `Other Global Options`

I'll fix this later

**Comment by mkSaBtsy** [comment]
> ... apply `--debug` params to `Builder Options` -> `Global Options` -> `Other Global Options `

I've tryed that too. Doesn't work either.

>I'll fix this later
So there is something to fix? No need for hurry. I'm glad if I can help improving.
In the meantime I'm still able to build by cmd.

**Comment by github0null** [comment]
> So there is something to fix? No need for hurry. I'm glad if I can help improving.
In the meantime I'm still able to build by cmd.

Because i found that `output debug info` options was ignored by builder, so `--debug` args will be not passed to sdcc

I have fixed this in v3.9.0

You can use `Show Compiler Commadline` menu item to check your compiler base args

![image](https://user-images.githubusercontent.com/43022536/189801475-f9c3b43d-6437-4139-8552-0ff9c95fa378.png)

![image](https://user-images.githubusercontent.com/43022536/189801105-e572511f-408c-443d-b48d-8ab64c6ce5eb.png)

**Comment by mkSaBtsy** [comment]
>You can use Show Compiler Commadline menu item to check your compiler base args

I have been aware of the `Show Compiler CommandLine` entry of the context menu. However, bexause debug info was not put out although the `--debug` option was shown in the supposed `Compiler CommandLine`. So I guessed that the compiler / linker was not invoked with the commands that the output of this menu item claims to.

>I have fixed this in v3.9.0

Humble question: Are you sure? The STM8 debugger plugin is still complaining about DWARF error.
![grafik](https://user-images.githubusercontent.com/38809530/189950503-fc226b98-22a6-4b36-97ec-d4073e357d80.png)

When I manally enter the commands everythins seems shiny.
![grafik](https://user-images.githubusercontent.com/38809530/189953072-8ab19c31-7fba-4ec7-9823-389468a7e7f8.png)

**Comment by github0null** [comment]
> Dwarf Error: xxxxx 

This is an unusual mistake

When i use sdcc v4.2.0, it tell me this error

But debugging information already exists in ELF

![image](https://user-images.githubusercontent.com/43022536/190165148-89b8a536-43db-4298-9e96-58b67d59831e.png)

When i use sdcc v4.0.0, it works

![image](https://user-images.githubusercontent.com/43022536/190164748-4b0e0a97-2648-414b-be5a-33f7e8669ad9.png)

---

I think the SDCC has some errors in processing debugging information in lib files.

In eide builder, after compiled all c source files, eide will make a lib file from all .rel file (not contain main.rel) 

And then, eide will use a command like `sdcc main.rel no_entry_bundled.rel` to link your elf/hex file

Because this operation will help sdcc reduce image size, ref: https://sourceforge.net/p/sdcc/discussion/1865/thread/e395ff7a42/#a03e

**Comment by mkSaBtsy** [comment]
>When i use sdcc v4.0.0, it works

Yeah, I can confirm that the debugger plugin doesn't complain about "DWARF error" when I use SDCC v4.0.0. However, v4.0..0 seems to generate different assembly code too. After switching back I was not even able to get my super simple "blinky" program to run with release config. The debugger plugin doesn't work too. With v4.2.0 the LED is blinking when built in "release" config and manually compiled I'm able to debug the code, at least with manually started openocd (see [here](https://github.com/github0null/stm8-debug/issues/13#issuecomment-1245901744)). So using the outdated compiler is not satisfying at all. Attached both .lst files from my blinky program:
[lst_comparison.zip](https://github.com/github0null/eide/files/9591247/lst_comparison.zip)

>And then, eide will use a command like sdcc main.rel no_entry_bundled.lib to link your elf/hex file

Is it possible to make a switch for activating and deactivating this feature? At least for my simple blinky program the .elf file generated by eide is some bytes bigger than that one I compiled manually. See below:
[elf_comparison.zip](https://github.com/github0null/eide/files/9591249/elf_comparison.zip)

**Comment by github0null** [comment]
> After switching back I was not even able to get my super simple "blinky" program to run with release config.

I can sure that compiler have no problems, because this plug-in was use v4.0.0 at the beginning

> Is it possible to make a switch for activating and deactivating this feature?

Sorry, I have no such plans in the near future

I think debug feature is not very necessary for sdcc, because sdcc does not well in debug.

And the `stm8-debug` gdb debugger is from stvp, sdcc not have a official gdb

**Comment by mkSaBtsy** [comment]
>I can sure that compiler have no problems, because this plug-in was use v4.0.0 at the beginning

I've the impression that the additional label(?) `__sdcc_gs_init_startup:` in line 59 is responsible for my problem. It is only generated by v4.0.0 not by v4.2.0. 
Unfortunately assembly is not my best known programming language. So I'm not able to determine what else is going on exactly in the .lst files.

>Sorry, I have no such plans in the near future
>I think debug feature is not very necessary for sdcc, because sdcc does not well in debug.
 
I see and I accept that. 

Then do you have a hint for me, why the same, yet very simple, code doesn't work in v4.0.0?
[Stm8_3.zip](https://github.com/github0null/eide/files/9591352/Stm8_3.zip)
Otherwise you can close this issue.

Thanks.
