### ISSUE TITLE
[bug] Cannot setup any utility tools, show "certificate has expired"

### ISSUE THREAD

**Issue by senhtry** [github0null/eide#291]
**What are you doing?**
Setup utility tools

**Describe the bug**
Cannot download any utility tools, show "certificate has expired"

**To Reproduce**
1. Go to 'EIDE' tool 
2. Click on 'Setup Utillity Tools'
3. Choose any tool, for example, the "GNU Arm Embedded Toolchian"

**Expected behavior**
Expect to automatic download tool

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 22H2
 - EIDE Version: v3.13.2023060401
 - VSCode Version: 1.83.1

**Comment by zskevind** [comment]
Still not work after upgraded to pre-release.

**Comment by ganyuanzhen** [comment]
Well, EIDE dose not connect to GitHub directly, Instead, it uses a proxy server. The certificate issue may be caused by this.

Simply set EIDE.Repository: Use Proxy to false.

This will let eide to connect to GitHub directly.

Or, edit the setting’s json file:
```
{
"EIDE.Repository.UseProxy": true
}
```
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Kevin ***@***.***>
发送时间: 2023年10月30日 15:26
收件人: ***@***.***>
抄送: Yuanzhen Gan ***@***.***>; ***@***.***>
主题: Re: [github0null/eide] [bug] Cannot setup any utility tools, show "certificate has expired" (Issue #291)


Still not work after upgraded to pre-release.

―
